### ISSUE TITLE
NTP configuration is missing in the terraform

### ISSUE THREAD

**Issue by spiarh** [SUSE/skuba#201]
Needless to say that NTP is fundamental for Kubernetes. 

This can be done with something like that in cloud-init + variables for the pools.

```yaml
ntp:
  enabled: true
  ntp_client: chrony
  pools: [0.pool.ntp.org, 1.pool.ntp.org, 2.pool.ntp.org]
```

**Acceptance criteria**

- [x] Nodes can be synchronized
- [x] NTP servers must be customizable as variables
